### ISSUE TITLE
Confirmed cases in covidPublicHealthData table

### ISSUE THREAD

**Issue by NielsNicolai** [Big-Life-Lab/PHES-ODM#82] opened 2021-01-27 14:07 UTC
Coming from the wastewater field, I have some trouble understanding the way individual test results should be reported in the data model. 

- Not sure if I understand the difference between `hospCen` and `hospAdm`. 
- What's the difference between `conf` and `posTest`?
- From what I understand, when reporting the number of confirmed cases using  `type` = `conf` it should be accompanied by a `dateType`. However, I don't understand the different options (`episode`, `onset`, `report`, `test`) which makes that I don't understand the use of the `dateType` variable...

Could someone try to give me a better explanation?

**Comment by NielsNicolai** [comment] 2021-03-03 17:09
@DougManuel @hswerdfe Could one of you elaborate a bit more on the terminology used to document the public health data?

**Comment by hswerdfe** [comment] 2021-03-03 17:45
I as well am unsure on the difference....

**Comment by hswerdfe** [comment] 2021-03-03 18:17
I as well am unsure on the difference....between` hospCen` and `hospAdm`.

`conf` is the number of confirmed positives cases in a given polygon on any given day, it will always be an integer >= 0

`posTest` is in theory going to be the same thing but it would normally be summarized from a tests dataset, also you would not be able to summarize tests by episode or onset date.

I am unsure how to expand on `dateType`, the description seems clear to me. so I am not sure how to elaborate.

**Comment by DougManuel** [comment] 2021-03-05 18:45
There are additional requests for individual line-list data. 

I work with the case data.

I'll address the issues above and add new table for individual line list table.

**Comment by mathew-thomson** [comment] 2022-02-17 20:44
I'll attempt to provide a series of definitions here to close this issue, as well as an update on how this data is stored for version 2. 

- Hospital Census (`hospCen`) is the number of people in hospital because of COVID-19 on a given date, while Hospital Admissions (`hospAdm`) is the number of specifically _new_ admissions on a given date.
- The difference here I am also somewhat unclear on, but I believe `conf` refers to a case that meets provincial standards (in Ontario that's gene target detection in a lab test, testing positive in a 'validated' point-of-care test, or seroconversion/antibody detection in a serology assay after previously not finding the antibody), whereas `posTest` just refers to the numb of positive tests from the labs.
- To differentiate here, `onset` is the date of symptom onset, `report` is the date the case was reported, `test` is the date of the positive test result, and `episode` (the most complicated) is the earliest date reported for a case, in the following order: Symptom Onset Date, Specimen Collection Date, or Test Confirmation Date.

This information is now being recorded in measures, however - specifically population measures. So further questions on this issue can be migrated over to issue #215 .

**Closed by mathew-thomson** 2022-02-17 20:44 UTC
Labels: question
