### ISSUE TITLE
Wide table metadata

### ISSUE THREAD

**Issue by DougManuel** [Big-Life-Lab/PHES-ODM#135] opened 2021-05-27 16:56 UTC
Should we develop a dictionary for wide table format?

There is currently just one variable that is specifically defined for wide format, `wwMeasureID`. 
However, we can add also add: 
- the translation of long to wide format.
- a list and description of common derived variables for wide table format. 

Suggestion for the name of this table, if we move forward?

See also #134.

**Comment by DougManuel** [comment] 2021-05-31 15:32
Decided at our working meeting to have this table. Flagged for v1.2

**Comment by jeandavidt** [comment] 2021-06-04 16:20
Here are my thoughts on the topic. We can discuss them in a meeting :) 

# Going from long to wide
Ideally, transferring from long to wide data format should be:
* As non-destructive as possible
* Simple (i.e., not too many rules)
* Systematic (Not too many exceptions to those rules)
* Should make it easier, not harder, to commit data to the data model and to then use that data.

The wide table is also the natural home of derived variables. This is because derived variables are constituted from one or more type(s) of measurements linked to the sample water sample, al of which should be aligned in the wide table, not so for the long table.

## Rules for variable names:
1. The column name should begin with the name of the source table for that column. The table name should be in `TitleCase`.
2. Each of the other bits of the column name should be in `pascalCase`.
3. Each part of wide table names should be separated by an `_`character.

This covers most of the column names already. For example, in the  `Site` table:
	* `Site_siteID`
	* `Site_name`
	* `Site_notes`
	* etc.
However, tables that have a 1-to-n relation with the Sample or the Site table, like WwMeasure a SiteMeasure, pose two problems that must be addressed:
1. **Some columns contain different kinds of information** (i.e., the `value`column of the WwMeasure table and of the SiteMeasure table contain data for suspended solids, viral concentrations, etc.
2. Different rows of these tables may contain different iterations of the same piece of data. For example, suspended solids can be measure three times on the same sample. Therefore, to brings those three items into the same celle of a wide table, **they need to be aggregated somehow**. 

### Thinking about how to spread a long column into several wide columns
The way I see it, there are three kinds of columns in a long table:
1. Identity columns that give to the row a unique ‘address’
2. Qualifying columns that describes what the row contains
3. The actual data that the row is trying to express.
For WwMeasure, the break-down looks like this:
* Identity columns:
	* `wwMeasureID`
	* `index`
	* `sampleID`
	* `analysisDate`
	* `reportDate`
* Qualifying columns:
	* `type`
	* `unit`
	* `aggregation`
	* `aggregationOther`
* Data columns:
	* `value`
	* `qualityFlag`
	* 	* `notes`
Put another way, **identity columns** help you place the value in the right *row*, **qualifying columns** create the *column name*, and the **data columns** contain the value that’s actually placed **in** the table. In some ways, categorizing columns into those groups is a matter of perspective. 

### Aggregating long data into a wide cell
To bring several data points into a single table cell we have to make choices. Either we maintain the integrity of the data by recording a list of values, or we aggregate the values into a single metric.
The value could be aggregated into a mean, a standard deviation, a median, etc.
Of course, aggregate statistics are **destructive**, meaning that the original data points from the long table can’t be recovered from the wide table.
Another way to deal with the problem is to create as many columns in the wide column as there are replicates for the measurement that has the most replicates. However, this yield a truly **wide** table which can be difficult to use (a lot of NaNs)
Of course, the aggregate statistics can only be applied to numerical (arguably, maybe to dates too). For text values, a list of values is a viable option.
Another way is to store the data in **key:value pairs**:
For numerical values, these key:value pairs could have the following form:
```
{
	'mean': 20.0,
	'std': 3.2,
	'median': 19,
	'n': 5,
}
```
For non-numerical data, the key value pair could hold the number off instances of each unique value. It could therefore be structured as such for a ’notes’ field aggregating five rows of a long table: 
```
{
	'Snowmelt day': 1,
	'Operator is drunk again. Filled the bottle with Diet Dr. Pepper. Still hasn't stopped giggling.': 2,
	'': 2,
}
```
The issue with these key value pairs is that:
1. They are hard to implement in excel (a cell  in Excel really should only hold one value)
2. They are hard to deal with in pandas (columns that hold complex objects can’t be sorted 
#### My current approach (`ODM-Import`):
Because I mostly want to create time series, I do the following:
1. I aggregate the values into a **mean**
2. I signal the aggregation in the column header. (`single-to-mean`)
### Putting it all together
The total formula for column naming is therefore the following:
```
name = TableName_qualifierOne_..._qualifier_N_aggregationName_dataColumnName
```
For `WwMeasure`, final wide column names could look like this:
```
WWMeasure_wqTSS_mgL_single-to-mean_value,
WWMeasure_wqNH4N_mgL_single-to-mean_qualityFlag,
WWMeasure_covN2_gcMl_single-to-mean_notes
```
## Derived variables
To identify the derived variables, I propose we:
1. Identify with the word `Calculated`in the spot where the table of origin should be, since they can be made up of several columns coming from different tables.
2. There are two ways that I can see derived variables be named:
	1. Declaring the full data transformation that yielded the values in the column, e.g.:
`Calculated_WWMeasure_covN2_gcMl_single-to-mean_value_dividedBy_SiteMeasure_wwFlow_m3d_single-to-mean_value`
	2. Using a short `nickname` to refer to the data transformation. That nickname would then have to be defined elsewhere in the ODM dictionary, e.g: `Calculated_covN2_normByFlow_gD_value`

**Comment by DougManuel** [comment] 2021-06-07 14:04
In addition:
- should be able to go from wide to long.

We discussed:
-  having short names for at least some tables in the wide table format. See #128 
- always including the table name for wide variables. Derived variables wouldn't need a table name - which is handing for identifying them as wide, derived variables.


Additional comments:

`2. Different rows of these tables may contain different iterations of the same piece of data. For example, suspended solids can be measure three times on the same sample. Therefore, to brings those three items into the same cells of a wide table, they need to be aggregated somehow.`

Rows can be maintained in wide table format with `index`, but we would need to be clear about how the index is used.

Re: "Putting it all together" and "Derived variables"
- I suggest `_single-to-mean_` could just be _mean_. It is helpful to include a number of samples as a variable. 
- `Calculated` is a good idea, but I tend toward omitting if all non-calculated measures have a table name included. There could be a few variables that are truly unique for wide tables, such as the number or replicates and uUID. In those situations, we could use 'Wide_` prefix.
- We could use nicknames and list the nicknames in the Wide metadata table.

**Comment by DougManuel** [comment] 2021-06-07 15:31
1) We will make a suggestion to use long and wide tables together. Long tables provide detail (i.e. replicates), wide tables provide summaries and derived measures (i.e. mean). 

You don't necessarily need to have all information in both, but you can if you want. 

2) Develop short table names: `WWMeasures` becomes `WWM`.

3) Have a nickname table and or explicit definition of how a derived measure was made. 

4) Last suffix in a wide variable describes the column name. i.e. _value.

5) Undecided on prefix. Discussed were: 

`covidN1_PPMV_mean_value`

`Wide_covidN1_PPMV_mean_value`

`calculated_covidN1_PPMV_mean_value`

**Closed** 2023-03-30 16:15 UTC
Labels: enhancement
