### ISSUE TITLE
Replicate type identification

### ISSUE THREAD

**Issue by davidchampredon** [Big-Life-Lab/PHES-ODM#94] opened 2021-02-01 19:53 UTC
(Suggestion, not entirely sure this is necessary, but the `sampleID` does not seem to identify the type of replicate, if there is more than one replicate)

Add a field either in the `sample` table or `WWMeasure` to specify the type of replicate: biological (true) replicate, pseudo-replicate (composite) and sub-sample (technical rep).

**Comment by vipileggi** [comment] 2021-02-02 19:22
@davidchampredon I agree. This is currently missing. We could use 'replicateType' for a category name and use the proposed names (biological, composite, technical, etc.) once we agree on the definitions.

**Comment by NielsNicolai** [comment] 2021-02-03 19:45
@davidchampredon could you elaborate a bit more on the definitions of the proposed replicate types?

**Comment by vipileggi** [comment] 2021-02-05 02:49
@davidchampredon @NielsNicolai a source that may help start the conversation. From Table 6.3 in [US EPA For Non-chemist](https://clu-in.org/conf/tio/rcraexpert_100516/slides/Data-Review-Manual-110114.pdf). Considering the list below I would classify 1. as a 'true' field replicate; 2. as a subsample of a single field sample' and 3-5 are 'analytical lab replicates' for QA/AC.

1. 'Co-located Samples-Second or multiples samples collected at same location but different time (water, air) or at a nearby location (soil, sediment). Sent blind to laboratory.'
2.'Field replicate: A sample divided into two or more homogeneous parts.'
3. ' Matrix Spike Duplicate (MSD): A known amounts of an analyte or representative compounds are added in the laboratory to a second aliquot of the sample used for matrix spike.'
4. 'Laboratory Control Sample Duplicate (LCSD): Known amounts of an analyte or representative compounds are added to a second "clean" matrix (lab water or clean sand) in laboratory. Duplicate of LCS'
5. 'Laboratory Duplicate (Replicate): Second (time or more) processing and analysis of sample. Usually for general chemistry or metals analyses.'

If the goal is to get a representative sample the ideal situation (I think) is to collect co-located samples (e.g., 24-h composite samples). Analyzing the composite sample seems to be the efficient way to proceed. Reporting the results of the analysis, based on some previous discussions with @davidchampredon, doing triplicate analyses ('analytical replicate' and some have referred to it as a 'technical replicate') on a representative sub-sample of the composite field sample and reporting all three values is recommended.

**Comment by vipileggi** [comment] 2021-03-02 15:32
@davidchampredon will add replicateID to WWMeasure. The options will be  modifications to those suggested by @davidchampredon : 1. trueReplicate: time separated sample taken at the same field location and not composited; 2. compReplicate:  subsamples taken from a single large grab or composite field sample; 3. techReplicate: analytical subsample result from a single primary sample. Although there may be others I think these are the primary three we need to distinguish for WW surveillance.

**Comment by NielsNicolai** [comment] 2021-03-03 17:23
Hmm I'm still not completely following. @DougManuel could we put this on the agenda for the next steering group meeting?

**Comment by mathew-thomson** [comment] 2022-02-15 22:23
We added two new fields to the "SampleReport" table, one is called 'origin' which has 'derived', 'field', and 'synthetic' as valid input values. The other field is 'replicateType', which has 'colocated', 'fieldReplicate', 'msd', 'lcsd', 'labDuplicate', and 'unique' as valid input values. We think that this structure (together with the parent-child relationship captured in the table) should be able to record this information well.

**Closed by mathew-thomson** 2022-02-15 22:23 UTC
Labels: enhancement
